config/routes.rb
Rails.application.routes.draw do
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@jobs = Job.all
		render :index
	end

	def new
		@job = Job.new
	end
	
	def create
		@job = Job.create(job_params)
		redirect_to jobs_path
	end

private

def job_params
	return params.require(:job).permit(:title, :description)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<h1> Jobs Index</h1>
<h2> You can see all of the jobs here</h2> 

<% @jobs.each do |job| %>
  <h3><%= job.title.downcase %></h3>
  <p><%= job.description %></p>
<% end %>

app/views/jobs/new.html.erb
<h1> New Job Form!!</h1> 

<%= form_for @job do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description, size: '60x6' %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobs for the Jobless</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

</head>
    
    <body>
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
    </body>

<header class='clearfix'>
  <div class="left-nav">
    <ul>
      <li><%= link_to "Home", jobs_path %></li>
    </ul>
  </div>
  <div class="right-nav">
    <ul>
      <li><%= link_to "Add Job", new_job_path %></li>
    </ul>
  </div>
</header>	



<div class ='content'>
<%= yield %>
</div>

</body>
</html>